AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 160
  Exclude: [spec/**/*.rb]

Lint/AssignmentInCondition:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpecialGlobalVars:
  Enabled: false

Style/Documentation:
  Enabled: false
